config/routes.rb
Jets.application.routes.draw do
  # get 'greetings', to: 'greetings#index'
  root "greetings#index"

  resources :greetings, only: [] do
    collection do
      get 'search'
    end
  end

  # root to: 'pictures#index'


  # The jets/public#show controller can serve static utf8 content out of the public folder.
  # Note, as part of the deploy process Jets uploads files in the public folder to s3
  # and serves them out of s3 directly. S3 is well suited to serve static assets.
  # More info here: https://rubyonjets.com/docs/extras/assets-serving/
  any "*catchall", to: "jets/public#show"
end

app/models/application_item.rb
class ApplicationItem < Dynomite::Item
end

app/controllers/application_controller.rb
class ApplicationController < Jets::Controller::Base
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  def index
    @random = "https://source.unsplash.com/random"
    @photos = random
  end

  # ９０枚の検索結果を取得
  def search
    @photos = []
    3.times do |i|
      search_results = Unsplash::Photo.search(params[:keyword], page = (i+1), per_page = 30)
      search_results.each do |photo|
        @photos << photo
      end
    end
    @photos = random if @photos.size == 0
  end

  def random
    photos = []
    3.times do |i|
      search_results = Unsplash::Photo.random(count: 30)
      search_results.each do |photo|
        photos << photo
      end
    end
    return photos
    
  end

  Unsplash.configure do |config|
    config.application_access_key = ENV["UNSPLASH_APPLICATION_ACCESS_KEY"]
    config.application_secret = ENV["UNSPLASH_APPLICATION_SECRET"]
    config.application_redirect_uri = "https://your-application.com/oauth/callback"
    config.utm_source = "image-falling-app"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/greetings/index.html.erb
<input id='menu' type='checkbox' class='checkbox' />
<div class='start-screen'>
  <div class='app-title'>
    <%= 'Eureka' %>
  </div>
  <%= form_with(url: search_greetings_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder:"keyword", class: "search-input" %>
    <%= form.submit "search", class: "search-btn" %>
  <% end %>
  <label for='menu' class='open' >
    <div class='start-btn'>
      <%= 'START' %>
    </div>
  </label>
  <div class='icon-space'>
    <img alt="Eureka-icon" src="https://coffee-ristretto.s3-ap-northeast-1.amazonaws.com/uploads/profile/image/16/eureka-icon.png", class='eureka-icon' />
  </div>
</div>

  
<div class='main-contents'>
  <% photos = @photos%>
  <% photos.each_with_index do |photo , n| %>
  <div class='at-container'>
    <div class='at-item ani-option<%="#{n}"%>'>
      <%=  image_tag photo.urls.thumb ,class: "size-option#{n}", style: 'opacity: unset;' %> 
    </div>
  </div>
  <% end %>
</div>

app/views/greetings/search.html.erb
<div class='search-contents'>
  <% photos = @photos%>
  <% photos.each_with_index do |photo , n| %>
  <div class='at-container'>
    <div class='at-item ani-option<%="#{n}"%>'>
      <%=  image_tag photo.urls.thumb ,class: "size-option#{n}", style: 'opacity: unset;' %> 
    </div>
  </div>
  <% end %>
</div>